version: "3"
services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile.rp
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
  php-composer:
    image: "composer"
    volumes:
      - "./nftup:/app"
    command: install
  php: # port 9000
    container_name: php
    build:
      dockerfile: Dockerfile.php
      depends_on:
        - db
  db: # port 3306
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env
